#include "port/interp.h"
#include "port/runtime.h"
#include "port/savestate.h"

#include <ctype.h>
#include <string.h>

/* Tables generated by tools/recomp (gen/<module>/table.c). */
#define NC_TABLE(mod)                                                                              \
    extern const NcFuncEntry mod##_table[];                                                        \
    extern const unsigned mod##_table_len;
NC_TABLE(slus_005_82)
NC_TABLE(psx_exe)
NC_TABLE(psx2_exe)
NC_TABLE(credits_exe)
NC_TABLE(stream1_exe)
NC_TABLE(stream2_exe)
NC_TABLE(stream3_exe)

typedef struct ModuleInfo {
    const char *exe;
    const NcFuncEntry *table;
    const unsigned *len;
} ModuleInfo;

static const ModuleInfo modules[NC_MOD_COUNT] = {
    [NC_MOD_PSX] = {"PSX.EXE", psx_exe_table, &psx_exe_table_len},
    [NC_MOD_PSX2] = {"PSX2.EXE", psx2_exe_table, &psx2_exe_table_len},
    [NC_MOD_CREDITS] = {"CREDITS.EXE", credits_exe_table, &credits_exe_table_len},
    [NC_MOD_STREAM1] = {"STREAM1.EXE", stream1_exe_table, &stream1_exe_table_len},
    [NC_MOD_STREAM2] = {"STREAM2.EXE", stream2_exe_table, &stream2_exe_table_len},
    [NC_MOD_STREAM3] = {"STREAM3.EXE", stream3_exe_table, &stream3_exe_table_len},
};

static NcModule active = NC_MOD_NONE;

NcModule nc_active_module(void) {
    return active;
}

void nc_set_module(NcModule mod) {
    active = mod;
    NC_LOG("module: %s", mod == NC_MOD_NONE ? "(none)" : modules[mod].exe);
}

static bool prefix_equal_nocase(const char *a, const char *b, size_t n) {
    for (size_t i = 0; i < n; i++) {
        if (tolower((unsigned char)a[i]) != tolower((unsigned char)b[i]) || a[i] == '\0') {
            return false;
        }
    }
    return true;
}

NcModule nc_module_from_name(const char *exe_name) {
    const char *base = strrchr(exe_name, '\\');
    base = base ? base + 1 : exe_name;
    for (int i = 0; i < NC_MOD_COUNT; i++) {
        size_t n = strlen(modules[i].exe);
        if (prefix_equal_nocase(base, modules[i].exe, n)) {
            return (NcModule)i;
        }
    }
    return NC_MOD_NONE;
}

static NcFunc search(const NcFuncEntry *table, unsigned len, u32 addr) {
    unsigned lo = 0, hi = len;
    while (lo < hi) {
        unsigned mid = (lo + hi) / 2;
        if (table[mid].addr < addr) {
            lo = mid + 1;
        } else {
            hi = mid;
        }
    }
    return (lo < len && table[lo].addr == addr) ? table[lo].fn : NULL;
}

NcFunc nc_lookup(u32 addr) {
    addr = (addr & 0x1FFFFFFFu) | 0x80000000u;
    if (addr >= NC_LAUNCHER_LO && addr < NC_OVERLAY_LO) {
        return search(slus_005_82_table, slus_005_82_table_len, addr);
    }
    if (active != NC_MOD_NONE) {
        return search(modules[active].table, *modules[active].len, addr);
    }
    return NULL;
}

void nc_call(CPUState *c, u32 addr) {
    switch (addr) {
    case 0xA0:
    case 0xB0:
    case 0xC0:
        bios_call(c, addr);
        return;
    default:
        break;
    }
    NcFunc fn = nc_lookup(addr);
    if (fn != NULL) {
        fn(c);
    } else {
        interp_call(c, addr); /* no native code for this address: interpret it */
    }
}

/* An indirect jump (jr) that is not a return: a tail call as far as the recompiler knows. */
void nc_jump(CPUState *c, u32 addr) {
    nc_call(c, addr);
}

void dispatch_serialize(StateIO *io) {
    STATE_VAR(io, active);
}
