#!/usr/bin/env python3
"""Generate splat configs (config/splat/*.yaml) for every game executable.

Segment boundaries are derived heuristically from the binaries:
  text start: first function prologue after the leading rodata
  text end:   after the last `jr $ra` / `jr $t2` (BIOS stub) plus its delay slot
"""

from __future__ import annotations

import hashlib
import struct
import sys
from pathlib import Path

import rabbitizer

ROOT = Path(__file__).resolve().parent.parent
DISC = ROOT / "build" / "disc"
OUT = ROOT / "config" / "splat"
HEADER_SIZE = 0x800
JR_RA = 0x03E00008
JR_T2 = 0x01400008

EXES = [
    "SLUS_005.82",
    "PSX.EXE",
    "PSX2.EXE",
    "CREDITS.EXE",
    "STREAM1.EXE",
    "STREAM2.EXE",
    "STREAM3.EXE",
]


def valid(word: int) -> bool:
    if word == 0:
        return True
    return rabbitizer.Instruction(word).isValid()


def is_prologue(word: int) -> bool:
    # addiu $sp, $sp, -N
    return (word & 0xFFFF8000) == 0x27BD8000


def looks_ascii(word: int) -> bool:
    raw = word.to_bytes(4, "little")
    return all(b in (0, 0x0A) or 0x20 <= b < 0x7F for b in raw) and any(raw)


def find_text(words: list[int]) -> tuple[int, int]:
    returns = [i for i, w in enumerate(words) if w in (JR_RA, JR_T2)]
    first, last = returns[0], returns[-1]
    # Walk back over valid instructions until a double-zero gap; string bytes in rodata
    # often decode as valid instructions too, so then skip forward past text-like words.
    start = first
    while start > 1 and valid(words[start - 1]) and not (words[start - 1] == words[start - 2] == 0):
        start -= 1
    while start < first and (looks_ascii(words[start]) and not is_prologue(words[start])):
        start += 1
    return start * 4, (last + 2) * 4


def gen(name: str) -> str:
    data = (DISC / name).read_bytes()
    pc, gp, t_addr, t_size = struct.unpack_from("<4I", data, 0x10)
    body = data[HEADER_SIZE:]
    words = list(struct.unpack(f"<{len(body) // 4}I", body))
    text_start, text_end = find_text(words)
    ts = HEADER_SIZE + text_start
    te = HEADER_SIZE + text_end
    base = name.lower().replace(".", "_")
    sha1 = hashlib.sha1(data).hexdigest()
    return f"""\
# Generated by tools/gen_splat.py; hand edits are fine, regeneration overwrites.
name: {name}
sha1: {sha1}
options:
  basename: {base}
  target_path: build/disc/{name}
  elf_path: build/splat/{base}.elf
  base_path: ../..
  platform: psx
  compiler: PSYQ
  asm_path: build/splat/{base}/asm
  src_path: src/decomp/{base}
  build_path: build/splat/{base}
  ld_script_path: build/splat/{base}.ld
  symbol_addrs_path:
    - config/symbols/{base}.txt
    - config/symbols/{base}.bios.txt
    - config/symbols/{base}.psyq.txt
  undefined_funcs_auto_path: build/splat/{base}/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/splat/{base}/undefined_syms_auto.txt
  find_file_boundaries: True
  section_order: [".rodata", ".text", ".data", ".bss"]
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
  # entry point 0x{pc:08X}
segments:
  - name: header
    type: header
    start: 0x0
  - name: main
    type: code
    start: 0x{HEADER_SIZE:X}
    vram: 0x{t_addr:08X}
    subsegments:
      - [0x{HEADER_SIZE:X}, rodata]
      - [0x{ts:X}, asm]
      - [0x{te:X}, data]
  - [0x{HEADER_SIZE + t_size:X}]
"""


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    (ROOT / "config" / "symbols").mkdir(parents=True, exist_ok=True)
    for name in EXES:
        if not (DISC / name).exists():
            print(f"missing {DISC / name}; run `make extract` first", file=sys.stderr)
            return 1
        base = name.lower().replace(".", "_")
        (OUT / f"{base}.yaml").write_text(gen(name))
        sym = ROOT / "config" / "symbols" / f"{base}.txt"
        if not sym.exists():
            sym.write_text("")
        print(f"wrote config/splat/{base}.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
