#!/usr/bin/env python3
"""Generate the interpreter's patch/hook table from config/patches.txt and config/hooks.txt.

The recompiler applies the same entries directly in the generated code; the interpreter looks
them up in this table instead. Usage: gen_patch_table.py <output.c>
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

MODULES = {
    "slus_005_82": "NC_PATCH_LAUNCHER",
    "psx_exe": "NC_MOD_PSX",
    "psx2_exe": "NC_MOD_PSX2",
    "credits_exe": "NC_MOD_CREDITS",
    "stream1_exe": "NC_MOD_STREAM1",
    "stream2_exe": "NC_MOD_STREAM2",
    "stream3_exe": "NC_MOD_STREAM3",
}


def entries(name: str) -> list[tuple[str, int, str]]:
    path = ROOT / "config" / name
    out = []
    for line in path.read_text().splitlines():
        fields = line.split("#", 1)[0].split()
        if len(fields) == 3:
            out.append((fields[0], int(fields[1], 16), fields[2]))
    return out


def main() -> int:
    patches = entries("patches.txt")
    hooks = entries("hooks.txt")
    lines = [
        "/* Generated by tools/gen_patch_table.py from config/; do not edit. */",
        '#include "port/interp.h"',
        '#include "port/runtime.h"',
        "",
    ]
    lines += [f"extern bool nc_flag_{f};" for f in sorted({p[2] for p in patches})]
    lines += [f"void nc_hook_{h}(CPUState *c);" for h in sorted({h[2] for h in hooks})]
    lines += ["", "const NcAddrPatch nc_addr_patches[] = {"]
    for mod, addr, hook in hooks:
        lines.append(f"    {{{MODULES[mod]}, 0x{addr:08X}u, nc_hook_{hook}, NULL}},")
    for mod, addr, flag in patches:
        lines.append(f"    {{{MODULES[mod]}, 0x{addr:08X}u, NULL, &nc_flag_{flag}}},")
    lines += ["};", f"const unsigned nc_addr_patch_count = {len(hooks) + len(patches)};", ""]
    Path(sys.argv[1]).write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
